# frozen_string_literal: true
ruby '2.7.6'

# Your gem dependencies here
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem "puma"
gem "sequel"
gem "json"
gem "bcrypt"
gem "jwt"
gem "byebug"
gem "rack-cors"
gem 'axlsx'
